/**
 * Phase 16C fixtures (ui/src/tests/fixtures/phase16c.json, generated by ui/scripts/capture_api_fixtures.py from the
 * real API over the sealed Phase 13 samples) and an MSW API that serves them by meaning, recording every request.
 */
import { http, type HttpHandler } from "msw";
import raw from "./fixtures/phase16c.json";
import type { AlertView, ListResponse, MarketIntelligenceView } from "../api/types";
import { authorized, respond } from "./msw";
import { fixture as phase13, type CapturedResponse } from "./fixtures";

export const f16 = raw as Record<string, CapturedResponse & { request: string }>;

export function fx(name: string): CapturedResponse & { request: string } {
  const entry = f16[name];
  if (!entry) throw new Error(`missing fixture ${name}`);
  return entry;
}

export function listBody<T>(name: string): ListResponse<T> {
  return fx(name).body as ListResponse<T>;
}

export const MI_ROWS = listBody<MarketIntelligenceView>("market-intelligence:history").data;
export const ALERT_ROWS = listBody<AlertView>("alerts:history").data;

type Family = "market-intelligence" | "alerts";

export interface Recorded {
  url: URL;
  authorization: string | null;
  requestId: string | null;
}

/** Overrides by fixture role, e.g. `{ "alerts:deliveries": fx("alerts:deliveries") }`. */
export function api16c(log: Recorded[] = [], overrides: Partial<Record<string, CapturedResponse>> = {}): HttpHandler[] {
  const pick = (name: string): CapturedResponse => overrides[name] ?? fx(name);
  const record = (request: Request): URL => {
    const url = new URL(request.url);
    log.push({ url, authorization: request.headers.get("Authorization"), requestId: request.headers.get("X-Request-ID") });
    return url;
  };
  const guard = (request: Request): CapturedResponse | null => (authorized(request) ? null : phase13("unauthorized"));
  const byId = (family: Family, id: string, kind: "detail" | "canonical"): CapturedResponse => {
    for (let i = 0; i < 3; i += 1) {
      const entry = f16[`${family}:${kind}:${String(i)}`];
      if (entry?.request.includes(`/${id}`)) return pick(`${family}:${kind}:${String(i)}`);
    }
    return pick(`${family}:not_found`);
  };
  return [
    http.get("*/health/live", () => respond(phase13("live"))),
    http.get("*/health/ready", () => respond(phase13("ready"))),
    http.get("*/api/v1/version", ({ request }) => respond(guard(request) ?? phase13("version"))),
    http.get("*/api/v1/:family/latest", ({ request, params }) => {
      const url = record(request);
      const denied = guard(request);
      if (denied) return respond(denied);
      const family = String(params.family) as Family;
      if (url.searchParams.get("symbol") === "META") return respond(pick(`${family}:latest`));
      return respond(pick(`${family}:latest_none`));
    }),
    http.get("*/api/v1/alerts/:id/deliveries", ({ request }) => {
      record(request);
      return respond(guard(request) ?? pick("alerts:deliveries_unavailable"));
    }),
    http.get("*/api/v1/:family/:id/canonical", ({ request, params }) => {
      record(request);
      return respond(guard(request) ?? byId(String(params.family) as Family, String(params.id), "canonical"));
    }),
    http.get("*/api/v1/:family/:id", ({ request, params }) => {
      record(request);
      return respond(guard(request) ?? byId(String(params.family) as Family, String(params.id), "detail"));
    }),
    http.get("*/api/v1/:family", ({ request, params }) => {
      const url = record(request);
      const denied = guard(request);
      if (denied) return respond(denied);
      const family = String(params.family) as Family;
      const q = url.searchParams;
      const cursor = q.get("cursor");
      if (cursor !== null) {
        const expected = listBody<unknown>(`${family}:page1`).meta.next_cursor;
        return respond(pick(cursor === expected ? `${family}:page2` : `${family}:bad_cursor`));
      }
      if (q.get("symbol") === "ZZZZ") return respond(pick(`${family}:empty`));
      if (q.has("as_of_from") || q.has("as_of_to")) return respond(pick(`${family}:window`));
      if (overrides[`${family}:first`]) return respond(pick(`${family}:first`));
      return respond(pick(`${family}:history`));
    }),
  ];
}

/** Only these query parameters exist on history (and only symbol/as_of on latest). */
export const HISTORY_PARAMS = new Set(["symbol", "as_of_from", "as_of_to", "limit", "cursor"]);
